apiVersion: v1
kind: Service
metadata:
  name: ml-fastapi-server-service
  namespace: argo
spec:
  type: ClusterIP
  # Uncomment the below line to create a Headless Service
  # clusterIP: None
  selector:
    app: ml-fastapi-server
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

